---
- name: Update version information in CMDB
  hosts: eos,nxos
  gather_facts: yes

  tasks:
    - name: Perform CMDB update
      servicenow.itsm.configuration_item:
        sys_id: "{{ sys_id }}"
        other:
          firmware_version: "{{ ansible_net_version }}"
